name: Build Eureka Kernel R9.2

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    # Bước này ép GitHub Actions bốc chính xác duy nhất nhánh R9.2_rom của Eureka về ngay từ đầu
    - name: Checkout Eureka Source (Branch R9.2_rom)
      uses: actions/checkout@v4
      with:
        repository: eurekadevelopment/Eureka-Kernel-Exynos7885-Q-R-S
        ref: R9.2_rom
        path: kernel-source

    - name: Install Dependencies
      run: |
        sudo apt update
        sudo apt install -y git ccache automake flex lzop bison build-essential zip curl zlib1g-dev libssl-dev libelf-dev bc ncurses-dev libncurses5-dev libncursesw5-dev squashfs-tools

    - name: Download Vortex Clang Toolchain
      run: |
        git clone https://github.com --depth=1 $GITHUB_WORKSPACE/vortex-clang

    - name: Build Kernel Binary
      run: |
        cd $GITHUB_WORKSPACE/kernel-source
        export ARCH=arm64
        export SUBARCH=arm64
        export CLANG_PATH=$GITHUB_WORKSPACE/vortex-clang/bin
        export PATH=$CLANG_PATH:$PATH
        export CROSS_COMPILE=aarch64-linux-gnu-
        export CROSS_COMPILE_ARM32=arm-linux-gnueabi-
        
        make clean && make mrproper
        make exynos7885_defconfig
        make CC=clang HOSTCC=clang-14 LD=ld.lld AR=llvm-ar NM=llvm-nm STRIP=llvm-strip OBJCOPY=llvm-objcopy OBJDUMP=llvm-objdump -j$(nproc)

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: Eureka-Kernel-R9.2-Image
        path: kernel-source/arch/arm64/boot/Image.gz-dtb
